import type { FileEntry } from "../types";

const typeMap: Record<string, string> = {
  txt: "Text Document",
  md: "Markdown Document",
  log: "Log File",
  csv: "CSV File",
  ts: "TypeScript File",
  tsx: "TypeScript JSX File",
  js: "JavaScript File",
  jsx: "JavaScript JSX File",
  rs: "Rust File",
  py: "Python File",
  html: "HTML File",
  css: "CSS File",
  json: "JSON File",
  toml: "TOML File",
  yaml: "YAML File",
  yml: "YAML File",
  xml: "XML File",
  png: "PNG File",
  jpg: "JPEG File",
  jpeg: "JPEG File",
  gif: "GIF File",
  svg: "SVG File",
  webp: "WebP File",
  bmp: "Bitmap File",
  ico: "Icon File",
  mp4: "MP4 Video",
  avi: "AVI Video",
  mkv: "MKV Video",
  mov: "QuickTime Video",
  webm: "WebM Video",
  mp3: "MP3 Audio",
  wav: "WAV Audio",
  flac: "FLAC Audio",
  ogg: "OGG Audio",
  zip: "ZIP Archive",
  "7z": "7-Zip Archive",
  rar: "RAR Archive",
  tar: "TAR Archive",
  gz: "GZ Archive",
  pdf: "PDF Document",
  doc: "Word Document",
  docx: "Word Document",
  xls: "Excel Spreadsheet",
  xlsx: "Excel Spreadsheet",
  ppt: "PowerPoint Presentation",
  pptx: "PowerPoint Presentation",
  exe: "Application",
  msi: "Windows Installer",
  dll: "DLL File",
  lnk: "Shortcut",
  bat: "Batch File",
  cmd: "Command Script",
  ps1: "PowerShell Script",
  clip: "CLIP STUDIO File",
  psd: "Photoshop File",
};

export function getFileType(entry: FileEntry): string {
  if (entry.is_dir) return "File Folder";
  if (!entry.extension) return "File";
  return typeMap[entry.extension] ?? `${entry.extension.toUpperCase()} File`;
}
