import type { FileEntry } from "../types";

const typeMap: Record<string, string> = {
  txt: "テキスト ファイル",
  md: "Markdown ソース ファイル",
  log: "ログ ファイル",
  csv: "CSV ファイル",
  ts: "TypeScript ソース ファイル",
  tsx: "TypeScript JSX ソース ファイル",
  js: "JavaScript ソース ファイル",
  jsx: "JavaScript JSX ソース ファイル",
  rs: "Rust ソース ファイル",
  py: "Python ソース ファイル",
  html: "Chrome HTML Document",
  css: "CSS ファイル",
  json: "JSON ソース ファイル",
  toml: "TOML ソース ファイル",
  yaml: "YAML ソース ファイル",
  yml: "YAML ソース ファイル",
  xml: "XML ファイル",
  png: "PNG ファイル",
  jpg: "JPEG ファイル",
  jpeg: "JPEG ファイル",
  gif: "GIF ファイル",
  svg: "SVG ファイル",
  webp: "WebP ファイル",
  bmp: "ビットマップ ファイル",
  ico: "アイコン ファイル",
  mp4: "MP4 ファイル",
  avi: "AVI ファイル",
  mkv: "MKV ファイル",
  mov: "QuickTime ファイル",
  webm: "WebM ファイル",
  mp3: "MP3 ファイル",
  wav: "WAV ファイル",
  flac: "FLAC ファイル",
  ogg: "OGG ファイル",
  zip: "ZIP アーカイブ",
  "7z": "7-Zip アーカイブ",
  rar: "RAR アーカイブ",
  tar: "TAR アーカイブ",
  gz: "GZ アーカイブ",
  pdf: "PDF ファイル",
  doc: "Word 文書",
  docx: "Word 文書",
  xls: "Excel スプレッドシート",
  xlsx: "Excel スプレッドシート",
  ppt: "PowerPoint プレゼンテーション",
  pptx: "PowerPoint プレゼンテーション",
  exe: "アプリケーション",
  msi: "Windows インストーラー",
  dll: "DLL ファイル",
  lnk: "ショートカット",
  bat: "バッチ ファイル",
  cmd: "コマンド スクリプト",
  ps1: "PowerShell スクリプト",
  clip: "CLIP STUDIO ファイル",
  psd: "Photoshop ファイル",
};

export function getFileType(entry: FileEntry): string {
  if (entry.is_dir) return "ファイル フォルダー";
  if (!entry.extension) return "ファイル";
  return typeMap[entry.extension] ?? `${entry.extension.toUpperCase()} ファイル`;
}
